name: safeguard_group3_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  camera: ^0.10.5+2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
