name: safeguard_group3_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+2
  email_validator: ^2.0.1
  flutter_map: ^0.13.1
  uuid: ^3.0.6

  flutter_calendar_carousel: ^2.2.1

  camera: ^0.10.5+2
  firebase_core: ^2.14.0
  firebase_ui_auth: ^1.4.3
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  image_picker: ^0.8.4+3
  permission_handler: ^10.3.0
  provider: ^6.0.5

  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  fluttertoast: ^8.2.2
  bcrypt: ^1.1.3
  crypto: ^3.0.3

#dependency_overrides:
#  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/SafeGuard logo.png

  uses-material-design: true

