name: safeguard_group3_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  loading_animation_widget: ^1.2.0+2
  firebase_auth: ^4.6.2
  email_validator: ^2.0.1
  flutter_map: ^0.13.1
  geolocator: ^8.0.0
  permission_handler: ^8.1.6
  uuid: ^3.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
